---
- hosts: localhost
  connection: local
  vars:
    # Constants
    exo_zone: CH-GVA-2
    exo_template: Linux Ubuntu 16.04 LTS 64-bit 50G Disk (2016-10-20-85bb6c)
    exo_instance_type: Micro
    # Parameters
    nb_nodes: "{{ cluster_init_nb_nodes }}"
  post_tasks:
    - name: Wait for the ssh to be up
      become: false
      local_action: wait_for host="{{ hostvars[item].ansible_host }}" port=22 timeout=90 delay=30
      with_items: "{{ groups['nodes'] }}"
  roles:
    - create-cluster
    - create-context

# Setup the nodes and install glusterfs
- hosts: nodes
  vars:
  roles:
    - setup-nodes

# Generate ssh key pair for the heketi user
- hosts: localhost
  connection: local
  vars:
    keypair_name: heketi
  roles:
    - generate-keypair

# Deploy heketi API on the nodes
- hosts: all
  become: True
  vars:
    # Heketi REST for glusterfs
    heketi_version: 1.0.1
    heketi_distribution: "heketi-{{ heketi_version }}.linux.amd64"
    heketi_mirror_url: "https://github.com/heketi/heketi/releases/download/"
    heketi_install_dir: "/usr/local"
    heketi_port: 8080
    # Standard file system bricks (no heketi)
    std_birck_nb: 1
  roles:
    - deploy-api

  - hosts: localhost
    connection: local
    post_tasks:
      - name: Export HEKETI_CLI_SERVER variable to use heketi-cli
        debug:
          msg: "export HEKETI_CLI_SERVER=http://{{ hostvars[groups['nodes'][0]]['ansible_host'] }}:8080"
      - name: Next... Load the topology
        debug:
          msg: "heketi-cli topology load --json=cluster-topology.json"
