  # Install partition management tools
  - name: Install partition management required packages
    apt:
      name: "{{ item }}"
      update_cache: yes
    tags: prt
    with_items:
      - expect
      - lvm2
      - thin-provisioning-tools
      - parted

  # Prepare the scripts
  - name: Create the partitioning scripts
    template:
      src: "{{ item }}.j2"
      dest: "/root/{{ item }}"
      owner: root
      group: root
      mode: 750
    with_items:
      - resize-partition
      - create-partition
    tags: prt

  # Check that the partition does not exists
  - name: Check for /dev/vda2
    command: parted -s /dev/vda print 2
    register: vda2
    failed_when: vda2.rc is not defined
    changed_when: >
      vda2.stdout == "Error: Partition doesn't exist."
    tags: prt

  # Execute the partitioning script
  - name: Execute the partitioning script
    shell: "./{{ item }}"
    args:
      chdir: /root/
    failed_when: false
    when: vda2.rc != 0
    with_items:
      - resize-partition
      - create-partition
    tags: prt
