
  # Make sure the mount location is created
  - name: Create the mount location
    file:
      path: "{{ gfs_volume_mount_dir }}"
      state: directory
      mode: 0775
      owner: root
      group: root
    tags: gfs-volume

  # Mount the new volume
  - name: Mount the volume for access
    mount:
      name: "{{ gfs_volume_mount_dir }}"
      src: "{{ hostvars[groups['nodes'][0]]['ansible_host'] }}:/{{ gfs_volume_name }}"
      fstype: glusterfs
      opts: "defaults,_netdev"
      state: mounted
    ignore_errors: true
    tags: gfs-volume
